### ISSUE TITLE
Does not run tests

### ISSUE THREAD

**Issue by AugustDev** [matt-ball/newman-action#12]
The action finishes in 1 second as success returning 

```
Run matt-ball/newman-action@master
  with:
    collection: e2e-views-backend.json
    environment: Development.postman_environment.json
    apiKey: postmanApiKey
    iterationCount: 1
    insecureFileRead: true
    timeout: Infinity
    timeoutRequest: Infinity
    timeoutScript: Infinity
    delayRequest: 0
    ignoreRedirects: false
    insecure: false
    bail: false
    suppressExitCode: false
    reporters: cli
    color: auto
  env:
    GOROOT: /opt/hostedtoolcache/go/1.15.0/x64
```

However no tests are done.

 I am using:

```
    - name: Performing E2E tests
      uses: matt-ball/newman-action@master
      with:
        collection: e2e-views-backend.json
        environment: Development.postman_environment.json
```
