### ISSUE TITLE
using "export-globals" 

### ISSUE THREAD

**Issue by gerome12** [matt-ball/newman-action#20]
Hi matt-ball,

I would like to use the option "export-globals" (https://github.com/postmanlabs/newman#command-line-options)

It's possible to adding this option to your GitHub Action ?

Thanks

Gérôme

**Comment by cynicaljoy** [comment]
The action supports all of the arguments exposed by the [Postman Newman NPM module](https://www.npmjs.com/package/newman):

Looking at the documentation, `--export-globals` is used when executing from the command line:

```
--export-globals <path>
The path to the file where Newman will output the final global variables file before completing a run.
```

but, when executing from the JavaScript API, you should be able to use:

````
options.globals | Postman Global Variables can be optionally passed on to a collection run in form of path to a file or URL. It also accepts variables as an object.

Type: object | string

````

So, something like the following will work:

```
- uses: actions/checkout@master
- uses: matt-ball/newman-action@master
  with:
    collection: postman_collection.json
    environment: postman_environment.json
    globals:   
        myProject:
            name: HelloWorld
            color: Yellow
```

**Comment by gerome12** [comment]
Hi cynicaljoy,

thanks for your reply

In my case, I have multiple collections and the first one get access tokens which are used by all the others.

My wish is to do something like that :

```
- uses: actions/checkout@master
- uses: matt-ball/newman-action@master
  with:
    collection: get_access_tokens_collection.json
    environment: postman_environment.json
    export-globals: my_globals_environment.json
- uses: matt-ball/newman-action@master
  with:
    collection: tests_1_collection.json
    environment: postman_environment.json
    globals: my_globals_environment.json
- uses: matt-ball/newman-action@master
  with:
    collection: tests_2_collection.json
    environment: postman_environment.json
    globals: my_globals_environment.json
```

Is this the right way to go?
