### ISSUE TITLE
running of action not catching/showing errors 

### ISSUE THREAD

**Issue by IgorGerasimov** [matt-ball/newman-action#3]
I have 2 problems with running Action 

1. it not display result ( any of possible `--reporters` options ` 
2. because of point 1 tests not failing job or step

```
Run matt-ball/newman-action@master
  with:
    collection: ./tests/Reference_Service.postman_collection.json
    environment: ./tests/integration.postman_environment.json
    iterationCount: 4
    reporters: cli
    bail: true
    apiKey: postmanApiKey
    insecureFileRead: true
    timeout: Infinity
    timeoutRequest: Infinity
    timeoutScript: Infinity
    delayRequest: 0
    ignoreRedirects: false
    insecure: false
    suppressExitCode: false
    color: auto
```
