### ISSUE TITLE
Run fails even though no tests failed

### ISSUE THREAD

**Issue by nev7n** [matt-ball/newman-action#42]
After upgrading to latest version the postman action fails, even though all tests passed:

```
    - name: Run postman tests
      uses: matt-ball/newman-action@master
      with:
        collection: 'Search Service Tests.postman_collection.json'
        environment: 'Local.postman_environment.json'
```
![image](https://user-images.githubusercontent.com/3842088/136777383-9c62f963-f196-4a6a-b7af-998ed8395770.png)

Reverting back to 0.3.7 and the tests pass:
```
    - name: Run postman tests
      uses: matt-ball/newman-action@v0.3.7
      with:
        collection: 'Search Service Tests.postman_collection.json'
        environment: 'Local.postman_environment.json'
```
