### ISSUE TITLE
`environment` does not accept a UUID

### ISSUE THREAD

**Issue by dadamsGS** [matt-ball/newman-action#49]
I am trying to run Newman in a GH Action using the same process as an example in the README:
```
- uses: actions/checkout@master
- uses: matt-ball/newman-action@master
  with:
    apiKey: ${{ secrets.postmanApiKey }}
    collection: ${{ env.COLLECTION }}
    environment: ${{ env.DEV }}
```

When I run the test in GH Actions I get the message:
```
Warning: Bad object passed in config!
Error: Newman run failed! Error: could not load environment
  ENOENT: no such file or directory, open '<my UUID>'
```

Am I missing something?
