### ISSUE TITLE
Specifying collection & environment via Postman API GUID not working

### ISSUE THREAD

**Issue by capelio** [matt-ball/newman-action#52]
When running the following job:

```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matt-ball/newman-action@v1.0.4
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: 2d8b8a29-29a7-4a70-8db7-615ad8e44874
          environment: 3d1532d7-22bd-4d50-99ea-4e66144530fd
```

I'm seeing the following error:

```
Newman run failed! Error: collection could not be loaded
  unable to read data from file "2d8b8a29-29a7-4a70-8db7-615ad8e44874"
  ENOENT: no such file or directory, open '2d8b8a29-29a7-4a70-8db7-615ad8e44874'
```

Any thoughts on why Newman's interpreting the GUIDs as file paths?
