### ISSUE TITLE
Use of `?.` syntax results in script error

### ISSUE THREAD

**Issue by throttlehead-dev** [matt-ball/newman-action#54]
This took us quite awhile to track down. It seems that whatever version of node this action is using might not support `?.` object accessor chaining.

For example:
```
questions[0]?.rules?.required
```

I tried ensuring node 16 was used within the job with an action we use elsewhere for our webpack builds:
```
    - name: Setup Node 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
```

But that didn't seem to fix the issue so it must be within the scope of this action. We ended up changing the test scripts for now but this might warrant an update on your end.

This is how we're using your action:
```
    - name: Run questionnaire_completions collection
      uses: matt-ball/newman-action@master
      with:
        collection: https://api.getpostman.com/collections/194034-4ed946cf-6c5e-4b6b-9524-0a5210e4fca3?apikey=${{ secrets.POSTMAN_API_KEY }}
        environment: ${{ secrets.POSTMAN_ENVIRONMENT}}
        workingDir: ./storage/tests/files/
```
