### ISSUE TITLE
private collection are not working as expected

### ISSUE THREAD

**Issue by gasparhe** [matt-ball/newman-action#65]
I'm trying to create a workflow like this:
```
- uses: actions/checkout@master
- uses: matt-ball/newman-action@master
  with:
    apiKey: ${{ secrets.postmanApiKey }}
    collection: 5922408-c22ef764-b464-424c-8702-750343478723
    environment: 5922408-228c7edd-fc15-4f68-9665-a35d7df6945b
```

but the service is failing processing the collection or the environment.
